/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerPerfil;
import controller.ControllerUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelPerfil;
import model.ModelUsuario;

/**
 *
 * @author Eduardo
 */
public class ViewUsuario extends javax.swing.JFrame {

    String altcboPerfil = "Listar";
    String perfil;
    ControllerPerfil controllerPerfil = new ControllerPerfil();
    ModelPerfil modelPerfil = new ModelPerfil();
    ArrayList<ModelPerfil> listaModelPerfis = new ArrayList<>();

    ControllerUsuario controllerUsuario = new ControllerUsuario();
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuarios = new ArrayList<>();
    String alterarSalvar;

    private int codigoPerfil;

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        carregarUsuarios();
        habilitarDesabilitarCampos(false);
        listarPerfil(altcboPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGUsuario = new javax.swing.ButtonGroup();
        jbPesquisar = new javax.swing.JButton();
        jbPesquisar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCBPerfil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtZap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarioTabela = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jRBNome = new javax.swing.JRadioButton();
        jRBPerfil = new javax.swing.JRadioButton();
        jtPesquisa = new javax.swing.JTextField();
        jbBusca = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/magnifier.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/cancel.png"))); // NOI18N
        jbPesquisar1.setText("Limpar");
        jbPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setResizable(false);

        jLabel1.setText("Código:");

        jTCodigo.setEditable(false);
        jTCodigo.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("Nome:");

        jLabel3.setText("Perfil:");

        jCBPerfil.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBPerfilPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jCBPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPerfilActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuário:");

        jLabel5.setText("Senha:");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/page.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/disk.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/application_edit.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/cross.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/stop.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Whatsapp:");

        jLabel7.setText("E-mail:");

        jTUsuarioTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Usuário", "Perfil", "Whatsapp", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTUsuarioTabela);
        if (jTUsuarioTabela.getColumnModel().getColumnCount() > 0) {
            jTUsuarioTabela.getColumnModel().getColumn(0).setMinWidth(0);
            jTUsuarioTabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTUsuarioTabela.getColumnModel().getColumn(2).setMinWidth(0);
            jTUsuarioTabela.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTUsuarioTabela.getColumnModel().getColumn(3).setMinWidth(15);
            jTUsuarioTabela.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTUsuarioTabela.getColumnModel().getColumn(4).setMinWidth(0);
            jTUsuarioTabela.getColumnModel().getColumn(4).setPreferredWidth(0);
        }

        jLabel8.setText("Pesquisar:");

        bGUsuario.add(jRBNome);
        jRBNome.setSelected(true);
        jRBNome.setText("Nome");

        bGUsuario.add(jRBPerfil);
        jRBPerfil.setText("Perfil");

        jbBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/magnifier.png"))); // NOI18N
        jbBusca.setText("Pesquisar");
        jbBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/cancel.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jCBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTUsuario)
                            .addComponent(jTSenha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jTEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jtZap)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(jRBNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBusca)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBPerfil)
                            .addComponent(jLabel8)
                            .addComponent(jRBNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLimpar)
                            .addComponent(jbBusca))
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBPerfilActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            modelUsuario.setId_usuario(Integer.parseInt(jTCodigo.getText()));
        } catch (NumberFormatException e) {
        }
        modelUsuario.setNome(jTNome.getText());
        modelUsuario.setPerfil(codigoPerfil);
        modelUsuario.setUsuario(jTUsuario.getText());
        modelUsuario.setSenha(jTSenha.getText());
        modelUsuario.setEmail(jTEmail.getText());
        modelUsuario.setWhatsapp(jtZap.getText());

        if (alterarSalvar.equals("salvar")) {
            if (controllerUsuario.salvarUsuarioController(modelUsuario) > 0) {
                JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarUsuarios();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (controllerUsuario.atualizarUsuarioController(modelUsuario)) {
                JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarUsuarios();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisar1ActionPerformed

    private void jbBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaActionPerformed
        if (jRBNome.isSelected()) {
            modelUsuario.setNome(jtPesquisa.getText());
            listaModelUsuarios = controllerUsuario.getListaUsuarioNomeController(modelUsuario);
        } else if (jRBPerfil.isSelected()) {
            modelUsuario.setNomePerfil(jtPesquisa.getText());
            listaModelUsuarios = controllerUsuario.getListaUsuarioPerfilController(modelUsuario);
        }
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarioTabela.getModel();
        modelo.setNumRows(0);
        int cont = listaModelUsuarios.size();
        if (cont == 0) {
            JOptionPane.showMessageDialog(this, "Não foi encontrado nenhum registro!", "Atenção", JOptionPane.WARNING_MESSAGE);
            //carregarUsuarios();
        } else {
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelUsuarios.get(i).getId_usuario(),
                    listaModelUsuarios.get(i).getNome(),
                    listaModelUsuarios.get(i).getNomePerfil(),
                    listaModelUsuarios.get(i).getWhatsapp(),
                    listaModelUsuarios.get(i).getEmail()
                });
            }
        }
    }//GEN-LAST:event_jbBuscaActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        jtPesquisa.setText("");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(this, "Deseja excluir o usuário?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            int linha = jTUsuarioTabela.getSelectedRow();
            int codigoUsuario = (int) jTUsuarioTabela.getValueAt(linha, 0);
            if (controllerUsuario.excluirUsuarioController(codigoUsuario)) {
                JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                this.carregarUsuarios();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o usuário", "ERRO", JOptionPane.ERROR);
            }
        }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        int linha = jTUsuarioTabela.getSelectedRow();
        int codigo = (int) jTUsuarioTabela.getValueAt(linha, 0);
        perfil = (String) jTUsuarioTabela.getValueAt(linha, 3);
        System.out.println(perfil);
        altcboPerfil = "Alterar";
        listarPerfil(altcboPerfil);
        modelUsuario = controllerUsuario.getUsuarioController(codigo);
        jTCodigo.setText(String.valueOf(modelUsuario.getId_usuario()));
        jTNome.setText(modelUsuario.getNome());
        jTEmail.setText(modelUsuario.getEmail());
        jCBPerfil.getSelectedItem();
        jTUsuario.setText(modelUsuario.getUsuario());
        jTSenha.setText(modelUsuario.getSenha());
        jtZap.setText(modelUsuario.getWhatsapp());
        alterarSalvar = "alterar";
        habilitarDesabilitarCampos(true);
        
        modelPerfil = controllerPerfil.getPerfilController(jCBPerfil.getSelectedItem().toString());
        codigoPerfil = modelPerfil.getCodPerfil();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos();
        habilitarDesabilitarCampos(true);
        altcboPerfil = "Listar";
        alterarSalvar = "salvar";
        jCBPerfil.removeAllItems();
        listarPerfil(altcboPerfil);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jCBPerfilPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPerfilPopupMenuWillBecomeInvisible
        if (jCBPerfil.isPopupVisible()) {
            modelPerfil = controllerPerfil.getPerfilController(jCBPerfil.getSelectedItem().toString());
            codigoPerfil = modelPerfil.getCodPerfil();
        }
    }//GEN-LAST:event_jCBPerfilPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    private void carregarUsuarios() {
        listaModelUsuarios = controllerUsuario.getListaUsuarioController();
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarioTabela.getModel();
        modelo.setNumRows(0);
        int cont = listaModelUsuarios.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelUsuarios.get(i).getId_usuario(),
                listaModelUsuarios.get(i).getNome(),
                listaModelUsuarios.get(i).getUsuario(),
                listaModelUsuarios.get(i).getNomePerfil(),
                listaModelUsuarios.get(i).getWhatsapp(),
                listaModelUsuarios.get(i).getEmail()
            });
        }
    }

    private void limparCampos() {
        jTCodigo.setText("");
        jTNome.setText("");
        jTEmail.setText("");
        jtZap.setText("");
        jtPesquisa.setText("");
        jTUsuario.setText("");
        jTSenha.setText("");
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        //jTCodigo.setEnabled(condicao);
        jTNome.setEnabled(condicao);
        jTEmail.setEnabled(condicao);
        jtZap.setEnabled(condicao);
        jTUsuario.setEnabled(condicao);
        jTSenha.setEnabled(condicao);
        jbSalvar.setEnabled(condicao);
        jCBPerfil.setEnabled(condicao);
    }

    // Preenche o combobox
    private void listarPerfil(String tipo) {
        System.out.println(tipo);
        if (tipo == "Listar") {
            listaModelPerfis = controllerPerfil.getListaPerfilController();
            jCBPerfil.removeAllItems();
            jCBPerfil.addItem("ESCOLHA");
            for (int i = 0; i < listaModelPerfis.size(); i++) {
                jCBPerfil.addItem(listaModelPerfis.get(i).getNome());
            }
        } else {
            listaModelPerfis = controllerPerfil.getListaPerfilController();
            jCBPerfil.removeAllItems();
            jCBPerfil.addItem(perfil);
            for (int i = 0; i < listaModelPerfis.size(); i++) {
                jCBPerfil.addItem(listaModelPerfis.get(i).getNome());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGUsuario;
    private javax.swing.JComboBox<String> jCBPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JRadioButton jRBPerfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTSenha;
    private javax.swing.JTextField jTUsuario;
    private javax.swing.JTable jTUsuarioTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBusca;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbPesquisar1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtZap;
    // End of variables declaration//GEN-END:variables
}
