/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerSolicitacaoGC;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import model.ModelSolicitacaoGC;

/**
 *
 * @author Lara Guedes
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        //this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
        setResizable(false);
        setLocationRelativeTo(null);
        pegarResolucao();
        new ViewLogin().dispose();
        jlblData.setText(getDataAtual());
        jlblDiaSemana.setText(getDiaSemana());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jlblNumeroSol = new javax.swing.JLabel();
        jbtnVerificar = new javax.swing.JButton();
        jlblData = new javax.swing.JLabel();
        jlblDiaSemana = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnClientes = new javax.swing.JButton();
        jbSGrandesClientes = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbnSair = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jmICadastroServicos1 = new javax.swing.JMenuItem();
        jmICadastroCliente = new javax.swing.JMenuItem();
        jmICadastroServicos = new javax.swing.JMenuItem();
        jmICadastroPerfil = new javax.swing.JMenuItem();
        jmICadastroServicos3 = new javax.swing.JMenuItem();
        jmICadastroCliente2 = new javax.swing.JMenuItem();
        jmICadastroServicos5 = new javax.swing.JMenuItem();
        jmICadastroServicos6 = new javax.swing.JMenuItem();
        jmICadastroServicos8 = new javax.swing.JMenuItem();
        jmICadastroServicos9 = new javax.swing.JMenuItem();
        jmICadastroServicos11 = new javax.swing.JMenuItem();
        jmICadastroServicos10 = new javax.swing.JMenuItem();
        jmICadastroServicos12 = new javax.swing.JMenuItem();
        jmICadastroServicos13 = new javax.swing.JMenuItem();
        jmICadastroServicos14 = new javax.swing.JMenuItem();
        jmICadastroServicos15 = new javax.swing.JMenuItem();
        jMenuGerencial = new javax.swing.JMenu();
        jmICadastroServicos2 = new javax.swing.JMenuItem();
        jmICadastroServicos4 = new javax.swing.JMenuItem();
        jmICadLigProv = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();
        jmIEquipeDesenv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(204, 204, 204));
        setExtendedState(6);
        setForeground(new java.awt.Color(204, 204, 204));
        setName("jfPrincipal"); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(2147, 1600));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Bem vindo:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Você tem");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("solicitações em aberto.");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/user.png"))); // NOI18N

        jlblUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(0, 102, 102));
        jlblUsuario.setText("recebe usuário");

        jlblNumeroSol.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlblNumeroSol.setForeground(new java.awt.Color(255, 51, 51));
        jlblNumeroSol.setText("xx");

        jbtnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/building_go.png"))); // NOI18N
        jbtnVerificar.setText("Verificar");
        jbtnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerificarActionPerformed(evt);
            }
        });

        jlblData.setForeground(new java.awt.Color(255, 0, 0));
        jlblData.setText("Recebe data");

        jlblDiaSemana.setForeground(new java.awt.Color(255, 0, 0));
        jlblDiaSemana.setText("Recebe dia semana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNumeroSol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDiaSemana))
                .addGap(34, 34, 34)
                .addComponent(jbtnVerificar)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jlblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblData)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNumeroSol)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jlblDiaSemana)))
                    .addComponent(jbtnVerificar))
                .addGap(8, 8, 8))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4});

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);

        jbtnClientes.setBackground(new java.awt.Color(255, 255, 255));
        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-diversos/Icones 256 WEB_2/dddasdfasdfasdf.png"))); // NOI18N
        jbtnClientes.setText("Cadastro de Clientes");
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnClientes);

        jbSGrandesClientes.setBackground(new java.awt.Color(255, 255, 255));
        jbSGrandesClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones 48 x 48/png/48x48/note_edit.png"))); // NOI18N
        jbSGrandesClientes.setText("Solicitações G.Clientes");
        jbSGrandesClientes.setToolTipText("");
        jbSGrandesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSGrandesClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jbSGrandesClientes);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones 48 x 48/png/48x48/Diagram.png"))); // NOI18N
        jButton5.setText("Gerar Relatórios");
        jToolBar1.add(jButton5);

        jbnSair.setBackground(new java.awt.Color(255, 255, 255));
        jbnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones 48 x 48/png/48x48/Exit.png"))); // NOI18N
        jbnSair.setText("Sair do Programa");
        jbnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(jbnSair);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo energisa.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(842, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-diversos/Gnome Icones/Icones XP/BlueSphere/32x32/apps/kedit.png"))); // NOI18N
        jMenuCadastro.setText("Cadastros (Edição)");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jmICadastroServicos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/user.png"))); // NOI18N
        jmICadastroServicos1.setText("Cadastro de Usuários");
        jmICadastroServicos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos1);

        jmICadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/group.png"))); // NOI18N
        jmICadastroCliente.setText("Cadastro de Grandes Clientes");
        jmICadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroCliente);

        jmICadastroServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos.setText("Cadastro de Serviços");
        jmICadastroServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos);

        jmICadastroPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/vcard.png"))); // NOI18N
        jmICadastroPerfil.setText("Cadastro de Perfis");
        jmICadastroPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroPerfilActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroPerfil);

        jmICadastroServicos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos3.setText("Cadastro de Outros");
        jmICadastroServicos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos3ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos3);

        jmICadastroCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/page_white_go.png"))); // NOI18N
        jmICadastroCliente2.setText("Cadastro de Formas de Devolução");
        jmICadastroCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroCliente2ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroCliente2);

        jmICadastroServicos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos5.setText("Cadastro de Agrupamentos");
        jmICadastroServicos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos5ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos5);

        jmICadastroServicos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos6.setText("Cadastro de Atividades");
        jmICadastroServicos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos6ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos6);

        jmICadastroServicos8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos8.setText("Cadastro de Classes");
        jmICadastroServicos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos8ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos8);

        jmICadastroServicos9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos9.setText("Cadastro de Grupos");
        jmICadastroServicos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos9ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos9);

        jmICadastroServicos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos11.setText("Cadastro de Grupos de Solicitações");
        jmICadastroServicos11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos11ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos11);

        jmICadastroServicos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos10.setText("Cadastro de Prioridades");
        jmICadastroServicos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos10ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos10);

        jmICadastroServicos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos12.setText("Cadastro de Regiões");
        jmICadastroServicos12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos12ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos12);

        jmICadastroServicos13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos13.setText("Cadastro de Subestações");
        jmICadastroServicos13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos13ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos13);

        jmICadastroServicos14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos14.setText("Cadastro de Subgrupos");
        jmICadastroServicos14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos14ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos14);

        jmICadastroServicos15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/text_list_numbers.png"))); // NOI18N
        jmICadastroServicos15.setText("Cadastro de Zonas");
        jmICadastroServicos15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos15ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jmICadastroServicos15);

        jMenuBar1.add(jMenuCadastro);

        jMenuGerencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-diversos/Gnome Icones/Icones XP/BlueSphere/32x32/apps/sawfish-appearance.png"))); // NOI18N
        jMenuGerencial.setText("Gerencial");

        jmICadastroServicos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/table_multiple.png"))); // NOI18N
        jmICadastroServicos2.setText("Cadastro de Solicitações (Grandes Clientes)");
        jmICadastroServicos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos2ActionPerformed(evt);
            }
        });
        jMenuGerencial.add(jmICadastroServicos2);

        jmICadastroServicos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/tab_edit.png"))); // NOI18N
        jmICadastroServicos4.setText("Cadastro de Solicitações (Poder Público)");
        jmICadastroServicos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadastroServicos4ActionPerformed(evt);
            }
        });
        jMenuGerencial.add(jmICadastroServicos4);

        jmICadLigProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/tab_edit.png"))); // NOI18N
        jmICadLigProv.setText("Cadastro de Ligações Provisórias");
        jmICadLigProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmICadLigProvActionPerformed(evt);
            }
        });
        jMenuGerencial.add(jmICadLigProv);

        jMenuBar1.add(jMenuGerencial);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-diversos/Gnome Icones/Icones XP/BlueSphere/32x32/apps/kchart.png"))); // NOI18N
        jMenuRelatorios.setText("Relatórios");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/chart_bar.png"))); // NOI18N
        jMenu2.setText("Relatório de Clientes por cidade");
        jMenuRelatorios.add(jMenu2);

        jMenuBar1.add(jMenuRelatorios);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-diversos/Gnome Icones/Icones XP/BlueSphere/32x32/actions/contexthelp.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });

        jmIEquipeDesenv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/user_gray.png"))); // NOI18N
        jmIEquipeDesenv.setText("Equipe de Desenvolvimento");
        jmIEquipeDesenv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIEquipeDesenvActionPerformed(evt);
            }
        });
        jMenuSobre.add(jmIEquipeDesenv);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        setBounds(0, 0, 1806, 1133);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed

    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jmICadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroClienteActionPerformed
        new ViewCliente().setVisible(true);

    }//GEN-LAST:event_jmICadastroClienteActionPerformed

    private void jmICadastroPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroPerfilActionPerformed
        new ViewPerfil().setVisible(true);
    }//GEN-LAST:event_jmICadastroPerfilActionPerformed

    private void jmICadastroServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicosActionPerformed
        new ViewServico().setVisible(true);
    }//GEN-LAST:event_jmICadastroServicosActionPerformed

    private void jmICadastroServicos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos1ActionPerformed
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jmICadastroServicos1ActionPerformed

    private void jmICadastroServicos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos2ActionPerformed
        new ViewSolicitacaoGC().setVisible(true);
    }//GEN-LAST:event_jmICadastroServicos2ActionPerformed

    private void jmICadastroServicos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos3ActionPerformed

    private void jmICadastroCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroCliente2ActionPerformed

    private void jmICadastroServicos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos4ActionPerformed

    private void jmICadastroServicos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos5ActionPerformed

    private void jmICadastroServicos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos6ActionPerformed

    private void jmICadastroServicos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos8ActionPerformed

    private void jmICadastroServicos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos9ActionPerformed

    private void jmICadastroServicos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos10ActionPerformed

    private void jmICadastroServicos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos11ActionPerformed
        // TODO add your handling code here:
        new ViewGrupoSolicitacao().setVisible(true);
    }//GEN-LAST:event_jmICadastroServicos11ActionPerformed

    private void jmICadastroServicos12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos12ActionPerformed

    private void jmICadastroServicos13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos13ActionPerformed

    private void jmICadastroServicos14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos14ActionPerformed

    private void jmICadastroServicos15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadastroServicos15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmICadastroServicos15ActionPerformed

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerificarActionPerformed
        new ViewSolicitacaoGC().setVisible(true);
    }//GEN-LAST:event_jbtnVerificarActionPerformed

    private void jmIEquipeDesenvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIEquipeDesenvActionPerformed
        new ViewEquipe().setVisible(true);
    }//GEN-LAST:event_jmIEquipeDesenvActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed

    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jbSGrandesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSGrandesClientesActionPerformed
        new ViewSolicitacaoGC().setVisible(true);
    }//GEN-LAST:event_jbSGrandesClientesActionPerformed

    private void jbnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSairActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(this, "Deseja sair do sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }
    }//GEN-LAST:event_jbnSairActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void jmICadLigProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmICadLigProvActionPerformed
        // TODO add your handling code here:
        new ViewLigacoesProvisorias().setVisible(true);
    }//GEN-LAST:event_jmICadLigProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);

            }
        });
    }

    private void pegarResolucao() {
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        this.setSize((dimensao.width + 5), (dimensao.height - 38));

    }

    public String getDiaSemana() {
        String diaSemana = "";
        GregorianCalendar gc = new GregorianCalendar();
        int diaDaSemana = gc.get(GregorianCalendar.DAY_OF_WEEK);
        switch (diaDaSemana) {
            case 1:
                diaSemana = "Domingo";
                break;
            case 2:
                diaSemana = "Segunda-Feira";
                break;
            case 3:
                diaSemana = "Terça-Feira";
                break;
            case 4:
                diaSemana = "Quarta-Feira";
                break;
            case 5:
                diaSemana = "Quinta-Feira";
                break;
            case 6:
                diaSemana = "Sexta-Feira";
                break;
            case 7:
                diaSemana = "Sábado";
                break;
        }
        return diaSemana;
    }

    public String getDataAtual() {
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String data = simpleDateFormat.format(calendar.getTime());
        return data;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuGerencial;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbSGrandesClientes;
    private javax.swing.JButton jbnSair;
    private javax.swing.JButton jbtnClientes;
    private javax.swing.JButton jbtnVerificar;
    private javax.swing.JLabel jlblData;
    private javax.swing.JLabel jlblDiaSemana;
    public javax.swing.JLabel jlblNumeroSol;
    public javax.swing.JLabel jlblUsuario;
    private javax.swing.JMenuItem jmICadLigProv;
    private javax.swing.JMenuItem jmICadastroCliente;
    private javax.swing.JMenuItem jmICadastroCliente2;
    private javax.swing.JMenuItem jmICadastroPerfil;
    private javax.swing.JMenuItem jmICadastroServicos;
    private javax.swing.JMenuItem jmICadastroServicos1;
    private javax.swing.JMenuItem jmICadastroServicos10;
    private javax.swing.JMenuItem jmICadastroServicos11;
    private javax.swing.JMenuItem jmICadastroServicos12;
    private javax.swing.JMenuItem jmICadastroServicos13;
    private javax.swing.JMenuItem jmICadastroServicos14;
    private javax.swing.JMenuItem jmICadastroServicos15;
    private javax.swing.JMenuItem jmICadastroServicos2;
    private javax.swing.JMenuItem jmICadastroServicos3;
    private javax.swing.JMenuItem jmICadastroServicos4;
    private javax.swing.JMenuItem jmICadastroServicos5;
    private javax.swing.JMenuItem jmICadastroServicos6;
    private javax.swing.JMenuItem jmICadastroServicos8;
    private javax.swing.JMenuItem jmICadastroServicos9;
    private javax.swing.JMenuItem jmIEquipeDesenv;
    // End of variables declaration//GEN-END:variables
}
