/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerGrupoSolicitacao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelGrupoSolicitacao;

/**
 *
 * @author Nielson Soares
 * Data criação: 08/05/2020
 * 
 */
public class ViewGrupoSolicitacao extends javax.swing.JFrame {
    
    //Variável para auxiliar na atualização automática do ComboBox de Grupos de Solicitações.
    ViewSolicitacaoGC viewSolicitacaoGC = null;

    ControllerGrupoSolicitacao controllerGrupoSolicitacao = new ControllerGrupoSolicitacao();
    
    ModelGrupoSolicitacao modelGrupoSolicitacao = new ModelGrupoSolicitacao();
    
    ArrayList<ModelGrupoSolicitacao> listModelGrupoSolicitacaos = new ArrayList();

    String alterarSalvar;
    private int codigoPerfil;

    /**
     * Creates new form ViewServicos
     */
    public ViewGrupoSolicitacao() {
        initComponents();
        setLocationRelativeTo(null);
        carregarGruposSolicitacoes();
        habilitarDesabilitarCampos(false);
    }
    public ViewGrupoSolicitacao(ViewSolicitacaoGC viewSolicitacaoGC) {
        this.viewSolicitacaoGC = viewSolicitacaoGC;
        initComponents();
        setLocationRelativeTo(null);
        carregarGruposSolicitacoes();
        habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTCodigo = new javax.swing.JTextField();
        jTDescricaoGrupoSol = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTServicoTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviços");
        setResizable(false);

        jTCodigo.setEditable(false);
        jTCodigo.setBackground(new java.awt.Color(255, 255, 204));

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/page.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/disk.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/application_edit.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/cross.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/stop.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição do Grupo de Solicitações");

        jLabel2.setText("Código");

        jTServicoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTServicoTabela);
        if (jTServicoTabela.getColumnModel().getColumnCount() > 0) {
            jTServicoTabela.getColumnModel().getColumn(0).setMinWidth(0);
            jTServicoTabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTServicoTabela.getColumnModel().getColumn(1).setMinWidth(200);
            jTServicoTabela.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTDescricaoGrupoSol, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDescricaoGrupoSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos();
        habilitarDesabilitarCampos(true);
        alterarSalvar = "salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            modelGrupoSolicitacao.setCodGrupoSolicitacao(Integer.parseInt(jTCodigo.getText()));
        } catch (NumberFormatException e) {
        }
        modelGrupoSolicitacao.setDescricao(jTDescricaoGrupoSol.getText());
        //JOptionPane.showMessageDialog(this, "Descrição: " + modelServico.getDescricao() + modelServico.getPrazo() + modelServico.getCodPerfil(), "Atenção", JOptionPane.WARNING_MESSAGE);
        if (alterarSalvar.equals("salvar")) {
            if (controllerGrupoSolicitacao.salvarGrupoSolController(modelGrupoSolicitacao) > 0) {
                JOptionPane.showMessageDialog(this, "Grupo de solicitações cadastrado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                carregarGruposSolicitacoes();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
                if(viewSolicitacaoGC != null)
                    viewSolicitacaoGC.listarGruposSolicitacao("Listar");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o grupo de solicitações!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (controllerGrupoSolicitacao.atualizarGrupoSolController(modelGrupoSolicitacao)) {
                JOptionPane.showMessageDialog(this, "Grupo de solicitações alterado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                carregarGruposSolicitacoes();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
                if(viewSolicitacaoGC != null)
                    viewSolicitacaoGC.listarGruposSolicitacao("Listar");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o grupo de solicitações!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(this, "Deseja excluir o grupo selecionado?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            int linha = jTServicoTabela.getSelectedRow();
            int codigoServico = (int) jTServicoTabela.getValueAt(linha, 0);
            if (controllerGrupoSolicitacao.excluirGrupoSolController(codigoServico)) {
                JOptionPane.showMessageDialog(this, "Grupo de solicitações excluído com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                
                carregarGruposSolicitacoes();
                if(viewSolicitacaoGC != null)
                    viewSolicitacaoGC.listarGruposSolicitacao("Listar");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o grupo de solicitações", "ERRO", JOptionPane.ERROR);
            }
        }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        //jCBPrazo.removeAllItems();
        int linha = jTServicoTabela.getSelectedRow();
        int codigo = (int) jTServicoTabela.getValueAt(linha, 0);
        
        modelGrupoSolicitacao = controllerGrupoSolicitacao.getGrupoSolicitacaoController(codigo);
        jTCodigo.setText(String.valueOf(modelGrupoSolicitacao.getCodGrupoSolicitacao()));
        jTDescricaoGrupoSol.setText(modelGrupoSolicitacao.getDescricao());
        
        alterarSalvar = "alterar";
        habilitarDesabilitarCampos(true);
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewServico().setVisible(true);
            }
        });
    }

    private void carregarGruposSolicitacoes() {
        //listaModelServicos = controllerServico.getListaServicoController();
        listModelGrupoSolicitacaos = controllerGrupoSolicitacao.getListaGrupoSolicitacaoController();
        DefaultTableModel modelo = (DefaultTableModel) jTServicoTabela.getModel();
        modelo.setNumRows(0);
        
        for (int i = 0; i < listModelGrupoSolicitacaos.size(); i++) {
            modelo.addRow(new Object[]{
                listModelGrupoSolicitacaos.get(i).getCodGrupoSolicitacao(),
                listModelGrupoSolicitacaos.get(i).getDescricao()
            });
        }
    }

    private void limparCampos() {
        jTCodigo.setText("");
        jTDescricaoGrupoSol.setText("");
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        //jTCodigo.setEnabled(condicao);
        jTDescricaoGrupoSol.setEnabled(condicao);
        jbSalvar.setEnabled(condicao);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTDescricaoGrupoSol;
    private javax.swing.JTable jTServicoTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables

}