/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerPerfil;
import controller.ControllerServico;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelPerfil;
import model.ModelServico;

/**
 *
 * @author edube
 */
public class ViewServico extends javax.swing.JFrame {

    String perfil;
    int prazo;
    String altcboPerfil = "Listar";

    ControllerServico controllerServico = new ControllerServico();
    ModelServico modelServico = new ModelServico();
    ArrayList<ModelServico> listaModelServicos = new ArrayList<>();

    ControllerPerfil controllerPerfil = new ControllerPerfil();
    ModelPerfil modelPerfil = new ModelPerfil();
    ArrayList<ModelPerfil> listaModelPerfis = new ArrayList<>();

    String alterarSalvar;
    private int codigoPerfil;

    /**
     * Creates new form ViewServicos
     */
    public ViewServico() {
        initComponents();
        setLocationRelativeTo(null);
        carregarServicos();
        habilitarDesabilitarCampos(false);
        listarPerfis(altcboPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTCodigo = new javax.swing.JTextField();
        jTDescricaoServ = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBPrazo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCBPerfil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTServicoTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviços");
        setResizable(false);

        jTCodigo.setEditable(false);
        jTCodigo.setBackground(new java.awt.Color(255, 255, 204));

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/page.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/disk.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/application_edit.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/cross.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 16 x 16/stop.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição do Serviço");

        jLabel2.setText("Código");

        jLabel3.setText("Prazo (Dias)");

        jCBPrazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        jLabel4.setText("Perfil");

        jCBPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA" }));
        jCBPerfil.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                jCBPerfilPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCBPerfilPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTServicoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Serviço", "Prazo", "Perfil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTServicoTabela);
        if (jTServicoTabela.getColumnModel().getColumnCount() > 0) {
            jTServicoTabela.getColumnModel().getColumn(0).setMinWidth(0);
            jTServicoTabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTServicoTabela.getColumnModel().getColumn(1).setMinWidth(200);
            jTServicoTabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTServicoTabela.getColumnModel().getColumn(2).setMinWidth(0);
            jTServicoTabela.getColumnModel().getColumn(2).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTDescricaoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDescricaoServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos();
        habilitarDesabilitarCampos(true);
        altcboPerfil = "Listar";
        listarPerfis(altcboPerfil);
        alterarSalvar = "salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            modelServico.setCodServico(Integer.parseInt(jTCodigo.getText()));
        } catch (NumberFormatException e) {
        }
        modelServico.setDescricao(jTDescricaoServ.getText());
        modelServico.setPrazo(Integer.parseInt(jCBPrazo.getSelectedItem().toString()));
        modelServico.setCodPerfil(codigoPerfil);
        //JOptionPane.showMessageDialog(this, "Descrição: " + modelServico.getDescricao() + modelServico.getPrazo() + modelServico.getCodPerfil(), "Atenção", JOptionPane.WARNING_MESSAGE);
        if (alterarSalvar.equals("salvar")) {
            if (controllerServico.salvarServicoController(modelServico) > 0) {
                JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarServicos();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o serviço!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (controllerServico.atualizarServicoController(modelServico)) {
                JOptionPane.showMessageDialog(this, "Serviço alterado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarServicos();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o serviço!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(this, "Deseja excluir o serviço?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            int linha = jTServicoTabela.getSelectedRow();
            int codigoServico = (int) jTServicoTabela.getValueAt(linha, 0);
            if (controllerServico.excluirServicoController(codigoServico)) {
                JOptionPane.showMessageDialog(this, "Serviço excluído com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                this.carregarServicos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o serviço", "ERRO", JOptionPane.ERROR);
            }
        }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jCBPerfilPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPerfilPopupMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBPerfilPopupMenuCanceled

    private void jCBPerfilPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPerfilPopupMenuWillBecomeInvisible
        if (jCBPerfil.isPopupVisible()) {
            modelPerfil = controllerPerfil.getPerfilController(jCBPerfil.getSelectedItem().toString());
            codigoPerfil = modelPerfil.getCodPerfil();
        }
    }//GEN-LAST:event_jCBPerfilPopupMenuWillBecomeInvisible

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        //jCBPrazo.removeAllItems();
        int linha = jTServicoTabela.getSelectedRow();
        int codigo = (int) jTServicoTabela.getValueAt(linha, 0);
        prazo = (int) jTServicoTabela.getValueAt(linha, 2);
        perfil = (String) jTServicoTabela.getValueAt(linha, 3);
        altcboPerfil = "Alterar";
        listarPerfis(altcboPerfil);
        modelServico = controllerServico.getServicoController(codigo);
        jTCodigo.setText(String.valueOf(modelServico.getCodServico()));
        jCBPerfil.getSelectedItem().toString();
        jTDescricaoServ.setText(modelServico.getDescricao());
        //jCBPrazo.addItem(String.valueOf(modelServico.getPrazo()));
        alterarSalvar = "alterar";
        habilitarDesabilitarCampos(true);
        
        
        modelPerfil = controllerPerfil.getPerfilController(jCBPerfil.getSelectedItem().toString());
        codigoPerfil = modelPerfil.getCodPerfil();
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewServico().setVisible(true);
            }
        });
    }

    private void carregarServicos() {
        listaModelServicos = controllerServico.getListaServicoController();
        DefaultTableModel modelo = (DefaultTableModel) jTServicoTabela.getModel();
        modelo.setNumRows(0);
        int cont = listaModelServicos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelServicos.get(i).getCodServico(),
                listaModelServicos.get(i).getDescricao(),
                listaModelServicos.get(i).getPrazo(),
                listaModelServicos.get(i).getPerfil()
            });
        }
    }

    private void limparCampos() {
        jTCodigo.setText("");
        jTDescricaoServ.setText("");
        //jCBPrazo.addItem("ESCOLHA");
        //jCBPerfil.addItem("ESCOLHA");
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        //jTCodigo.setEnabled(condicao);
        jTDescricaoServ.setEnabled(condicao);
        jbSalvar.setEnabled(condicao);
        jCBPerfil.setEnabled(condicao);
        jCBPrazo.setEnabled(condicao);
    }

    // Preenche o combobox
    private void listarPerfis(String tipo){
        if (tipo == "Listar") {
            listaModelPerfis = controllerPerfil.getListaPerfilController();
            jCBPerfil.removeAllItems();
            jCBPerfil.addItem("ESCOLHA");
            for (int i = 0; i < listaModelPerfis.size(); i++) {
                jCBPerfil.addItem(listaModelPerfis.get(i).getNome());
            }
        } else {
            listaModelPerfis = controllerPerfil.getListaPerfilController();
            jCBPerfil.removeAllItems();
            jCBPerfil.addItem(perfil);
            for (int i = 0; i < listaModelPerfis.size(); i++) {
                jCBPerfil.addItem(listaModelPerfis.get(i).getNome());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBPerfil;
    private javax.swing.JComboBox<String> jCBPrazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTDescricaoServ;
    private javax.swing.JTable jTServicoTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables

}